const types = {
  RETRIEVE_COUNTRIES: "RETRIEVE_COUNTRIES",
  ADD_TO_MISSED_COUNTRIES: "ADD_TO_MISSED_COUNTRIES",
  RESET_MISSED_COUNTRIES: "RESET_MISSED_COUNTRIES",
  REMOVE_COUNTRY: "REMOVE_COUNTRY",
  GET_NEXT_COUNTRY: "GET_NEXT_COUNTRY",
  SET_CURRENT_QUESTION: "SET_CURRENT_QUESTION",
  ADD_TO_QUESTIONS_HISTORY: "ADD_TO_QUESTIONS:HISTORY",
  MARK_CORRECT: "MARK_CORRECT",
  MARK_WRONG: "MARK_WRONG",
  PROVIDE_ANSWER: "PROVIDE_ANSWER",
  RESET_COUNTRIES_ASKED: "RESET_COUNTRIES_ASKED",
  INCREMENT_COUNTRY_INDEX: "INCREMENT_COUNTRY_INDEX",
  DECREMENT_COUNTRY_INDEX: "DECREMENT_COUNTRY_INDEX",
  RESET_COUNTRY_INDEX: "RESET_COUNTRY_INDEX",
  VIEW_RESULTS: "VIEW_RESULTS",
  HIDE_RESULTS: "HIDE_RESULTS",
  RESET_REMAINING_COUNTRIES: "RESET_REMAINING_COUNTRIES",
};

export default types;
