const types = {
  RETRIEVE_ALL_QUESTIONS: "RETRIEVE_ALL_QUESTIONS",
  ADD_TO_MISSED_QUESTIONS: "ADD_TO_MISSED_QUESTIONS",
  RESET_MISSED_QUESTIONS: "RESET_MISSED_QUESTIONS",
  REMOVE_QUESTION: "REMOVE_QUESTION",
  GET_NEXT_QUESTION: "GET_NEXT_QUESTION",
  ADD_TO_QUESTIONS_HISTORY: "ADD_TO_QUESTIONS:HISTORY",
  MARK_CORRECT: "MARK_CORRECT",
  MARK_WRONG: "MARK_WRONG",
  PROVIDE_ANSWER: "PROVIDE_ANSWER",
};

export default types;
