const types = {
  RETRIEVE_ALL_QUESTIONS: "RETRIEVE_ALL_QUESTIONS",
  ADD_TO_MISSED_QUESTIONS: "ADD_TO_MISSED_QUESTIONS",
  RESET_MISSED_QUESTIONS: "RESET_MISSED_QUESTIONS",
  REMOVE_QUESTION: "REMOVE_QUESTION",
};

export default types;
